services:
  - type: web
    name: kemet-travel-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: kemet-data
      mountPath: /data
      sizeGB: 1 